/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rfst_ula
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RFST_ULA_API_H
#define INCLUDED_RFST_ULA_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rfst_ula_EXPORTS
#define RFST_ULA_API __GR_ATTR_EXPORT
#else
#define RFST_ULA_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RFST_ULA_API_H */
