/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(adaptive_doa_ula.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5641f60264cd3e646b1798ab5cde2d55)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/rfst_ula/adaptive_doa_ula.h>
// pydoc.h is automatically generated in the build directory
#include <adaptive_doa_ula_pydoc.h>

void bind_adaptive_doa_ula(py::module& m)
{

    using adaptive_doa_ula    = gr::rfst_ula::adaptive_doa_ula;


    py::class_<adaptive_doa_ula, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<adaptive_doa_ula>>(m, "adaptive_doa_ula", D(adaptive_doa_ula))

        .def(py::init(&adaptive_doa_ula::make),
           D(adaptive_doa_ula,make)
        )
        



        ;




}








